# Generated by Django 5.1.1 on 2024-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_product_image_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pda_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
