# Generated by Django 5.1.1 on 2024-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_brochure_alter_product_fdcimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='Abcd@1234', max_length=255),
        ),
    ]
